### ISSUE TITLE
Document expected result if bundle is true

### ISSUE THREAD

**Issue by fgblomqvist** [indooorsman/esbuild-css-modules-plugin#1]
The readme doesn't say what happens when `bundle: true`? There doesn't seem to be any code for even checking if bundle is true or false, nor for handling any `true` case (e.g. bundling into a single output file). Does this plugin only handle `bundle: false`?

**Comment by indooorsman** [comment]
@fgblomqvist Both `bundle: true` & `bundle: false` work. Refer to `[test/test.js](https://github.com/indooorsman/esbuild-css-modules-plugin/blob/master/test/test.js)` for examples.
