### ISSUE TITLE
Only injecting styles when esm module is used

### ISSUE THREAD

**Issue by AlfieJones** [indooorsman/esbuild-css-modules-plugin#18]
I'm using this library for a react library with multiple components. Currently all the styling of each component gets injected even if they're unused and not imported. How would I go about making the code inject tree shakable?

**Comment by indooorsman** [comment]
where do you import your components styles?

**Comment by AlfieJones** [comment]
Into the individual components. So components which aren't used still have their css imported

**Comment by indooorsman** [comment]
@AlfieJones hi, this issue should be fixed in `[v2.2.5](https://github.com/indooorsman/esbuild-css-modules-plugin/releases/tag/v2.2.5)`, please upgrade and try again with config `{v2: true, inject: true}`
