### ISSUE TITLE
Combine with less / sass

### ISSUE THREAD

**Issue by fragsalat** [indooorsman/esbuild-css-modules-plugin#31]
Hey there,

is there a way to make css modules work with less / scss?
If not it would be awesome to have a hook for pre processing to let less or scss compile the content to css before the plugin is processing the classes.

**Comment by indooorsman** [comment]
this plugin will handle `.module(s).css` with `file` namespace (https://esbuild.github.io/plugins/#namespaces) , it will do nothing if some other plugin resolve these files to another namespace.

for pre/post hooks I have to think more.

another approach is to compile less/sass to normal css before esbuild
