### ISSUE TITLE
Support SSR

### ISSUE THREAD

**Issue by lokimckay** [indooorsman/esbuild-css-modules-plugin#33]
# Issue

The default code generated when `inject = true` is not compatible with server side rendering

[Code in question](https://github.com/indooorsman/esbuild-css-modules-plugin/blob/ba1ef527896ecf4c83b6d6c653eef351d2fb1693/lib/v1.js#L57-L64)

```js
var digest = "...";
var css = `...`
(function() {
  if (!document.getElementById(digest)) {
    var el = document.createElement("style");
    el.id = digest;
    el.textContent = css;
    document.head.appendChild(el);
  }
})();
var styles_module_css_default = { ... };
```

If used in a non-browser context (e.g. NextJS SSR), this error is thrown:

`ReferenceError: document is not defined`
<img src="https://user-images.githubusercontent.com/14341953/167820256-099b9948-217d-479f-b600-5a2173108911.png" width="50%" />

# Desired

In order to support SSR, the code linked above should first check if the `document` object is available

# Workaround

Return a function as a string from the `inject` parameter that confirms that document is available before using it
(`if (typeof document !== \"undefined\" &&`)

```js
cssModulesPlugin({
  inject: (cssContent, digest) => {
    return `
    (function() {
      if (typeof document !== \"undefined\" && !document.getElementById(\`${digest}\`)) {
        var el = document.createElement("style");
        el.id = \`${digest}\`;
        el.textContent = \`${cssContent}\`;
        document.head.appendChild(el);
      }
    })();
    `;
  },
}),
```

Happy to open a PR if needed - let me know :smile:

**Comment by indooorsman** [comment]
fixed in `v2.3.1`, thanks a lot.
