### ISSUE TITLE
using different extensions

### ISSUE THREAD

**Issue by chrisdugne** [indooorsman/esbuild-css-modules-plugin#34]
hello, 
I need to use this plugin on `.css` files (without having to add `.modules.css`)
would it be possible to add as an option ?
(like here: https://github.com/koluch/esbuild-plugin-css-modules/blob/main/index.ts#L32)

thanks!

**Comment by indooorsman** [comment]
Hi @chrisdugne please try [v2.4.0](https://github.com/indooorsman/esbuild-css-modules-plugin/releases/tag/v2.4.0)

**Comment by chrisdugne** [comment]
sounds good ! thanks
