### ISSUE TITLE
Compatibility with classnames/bind

### ISSUE THREAD

**Issue by yourivdlans** [indooorsman/esbuild-css-modules-plugin#37]
Hi!

Currently I'm in the process of migrating a project from webpack to esbuild. The project is using css modules in combination with classnames/bind. This makes it easy to conditionally assign classes.

I'm trying to get this to work with this plugin but I'm unsuccesful so far. And I'm wondering if I'm just missing something or this approach is just not compatible right now.

Example component:

**styles.css**
```css
.hello-world {
  color: red;
}
```

**hello_world.jsx**
```jsx
import styles from 'styles.css';
import classNames from 'classnames/bind';

const cx = classNames.bind(styles);

export const HelloWorld = () => (
  <>
    <h3 className={cx('hello-world')}>Hello World!</h3>
  </>
);
```

The above example does not change the classname to a unique class.

I could use the following which works:

```jsx
<h3 className={cx(styles.helloWorld)}>Hello World!</h3>
```

But then I'm not sure how to conditionally enabled / disable a class.

The following does not work but putting it here to try to explain what I'm trying to reach:

```jsx
<h3 className={cx({styles.helloWorld: false})}>Hello World!</h3>
```

Curious if you have any suggestions!

**Comment by indooorsman** [comment]
I think it should be:
```
<h3 className={cx({ [styles.helloWorld]: false })}>Hello World!</h3>
```
