### ISSUE TITLE
Contribution: add support for named imports / exports

### ISSUE THREAD

**Issue by LucaColonnello** [indooorsman/esbuild-css-modules-plugin#39]
Many compilers guidelines recommend using named exports for CSS Modules, including Parcel.
Many third party UI libraries use this approach already.

This plugin doesn't currently support named import / exports for CSS Modules.
I made a PR to add support https://github.com/indooorsman/esbuild-css-modules-plugin/pull/38.

This does not allow tree-shaking, as mentioned in the description, but it allows the usage of the named import syntax when using CSS Modules, so that it bring full compatibility and parity with other compilers (such as Webpack and Parcel, which both support this option out of the box).

**Comment by LucaColonnello** [comment]
@indooorsman would you have some time to have a look at this?

Thank you! 🙏

**Comment by indooorsman** [comment]
merged, thanks a lot
