### ISSUE TITLE
ESBuild peer dependency issue 

### ISSUE THREAD

**Issue by abereghici** [indooorsman/esbuild-css-modules-plugin#41]
I have installed ESBuild version `0.15.1` and I'm not able to use the plugin. The following error is displayed:
```
npm ERR! Could not resolve dependency:
npm ERR! peer esbuild@"^0.14.38" from esbuild-css-modules-plugin@2.5.1
```

Is it possible to allow higher versions of esbuild as peer dependency or there are some restrictions?

**Comment by indooorsman** [comment]
@abereghici please try v2.5.2, thanks

**Comment by abereghici** [comment]
It's working, thanks!
