### ISSUE TITLE
Cannot find module '../lightningcss.linux-x64-gnu.node'

### ISSUE THREAD

**Issue by jacob-orbiit** [indooorsman/esbuild-css-modules-plugin#44]
An update to one of this packages' dependencies appears to have broken this package: https://github.com/parcel-bundler/lightningcss/issues/335

I see in your package.json, you're locked to `lightningcss@^1.16.0`: https://github.com/indooorsman/esbuild-css-modules-plugin/blob/main/package.json#L31

lightningcss recently released a patch (`1.16.1)`, which seems likely to blame: https://github.com/parcel-bundler/lightningcss/releases/tag/v1.16.1

Pinning to `1.16.0` explicitly may resolve the issue.

**Comment by indooorsman** [comment]
I can't reproduce this issue on my Mac Book, could you please provide more details about your case?
And if you want to lock version of lightningcss to 1.16.0 in your project, I think you could declare `resolutions` for `yarn` or `overrides` for `npm`

- https://yarnpkg.com/configuration/manifest#resolutions
- https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides

**Comment by jacob-orbiit** [comment]
It looks like pinning your dep won't matter because `lightningcss` were themselves not pinning their dep, which was the source of the breakage. Details are in the `lightningcss` PR linked in my original post (specifically https://github.com/parcel-bundler/lightningcss/issues/335#issuecomment-1320216228).

**Comment by indooorsman** [comment]
I've upgraded lightningcss to v1.17 which should have fixed your issue, please have a try with [v2.6.3](https://github.com/indooorsman/esbuild-css-modules-plugin/releases/tag/v2.6.3)

**Comment by jacob-orbiit** [comment]
It's back (I'm on [`v2.7.1`](https://github.com/indooorsman/esbuild-css-modules-plugin/releases/tag/v2.7.1)).

**Comment by indooorsman** [comment]
please  try `v3-dev`
________________________________
发件人: Jacob ***@***.***>
发送时间: Friday, August 11, 2023 5:47:54 PM
收件人: indooorsman/esbuild-css-modules-plugin ***@***.***>
抄送: indooorsman ***@***.***>; Comment ***@***.***>
主题: Re: [indooorsman/esbuild-css-modules-plugin] Cannot find module '../lightningcss.linux-x64-gnu.node' (Issue #44)


It's back (I'm on v2.7.1<https://github.com/indooorsman/esbuild-css-modules-plugin/releases/tag/v2.7.1>).

―

**Comment by jacob-orbiit** [comment]
> please try `v3-dev`

That seems to be totally b0rked. Not getting any errors. I see the css file is generated, but there are no classes in the final markup, so I'm thinking the imports are broken.

**Comment by jacob-orbiit** [comment]
Heads up to others: Adding the following to your package.json works around the issue (which I reported upstream https://github.com/parcel-bundler/lightningcss/issues/567)

```
"overrides": {
  "esbuild-css-modules-plugin": {
    "lightningcss": "1.21.3"
  }
}
```

**Comment by indooorsman** [comment]
@jacob-orbiit I see, it seems to be a bug of npm https://github.com/npm/cli/issues/4828 , please try:
```bash
rm -rf node_modules package-lock.json
npm install
```
