### ISSUE TITLE
`getBuildId` fails when `entryPoints` is undefined

### ISSUE THREAD

**Issue by markdalgleish** [indooorsman/esbuild-css-modules-plugin#46]
It's possible for `entryPoints` to be undefined because esbuild supports passing file contents via the `stdin` option. This plugin assumes that `entryPoints` exists when trying to generate a build ID, and if `stdin` is used instead it throws an error.

As an example of the `stdin` option being used, here's a code snippet from Remix internals:

```ts
  let stdin: esbuild.StdinOptions | undefined;
  let entryPoints: string[] | undefined;
  
  if (config.serverEntryPoint) {
    entryPoints = [config.serverEntryPoint];
  } else {
    stdin = {
      contents: config.serverBuildTargetEntryModule,
      resolveDir: config.rootDirectory,
      loader: "ts",
    };
  }
```

**Comment by indooorsman** [comment]
does it mean I can generate the build id from `stdin.contents` ?

**Comment by markdalgleish** [comment]
Yep, I believe so.
