### ISSUE TITLE
Composition support

### ISSUE THREAD

**Issue by stevecrozz** [indooorsman/esbuild-css-modules-plugin#50]
Is it intended that composition should be supported?

I have tried this syntax, but the property is not part of the generated output:
~~~
.myThing {
  padding-left: 25px;
}

.myOtherThing {
  composes: myThing;
}
~~~

I am running with the following config:
~~~
cssModulesPlugin({
  inject: false,
  v2: true,
})
~~~

**Comment by angrycat9000** [comment]
Just ran into this issue as well.  Had a class that composed a style from another file.  

```
.optionLabel {
  composes: label from "../../style/forms.module.css";
  display: inline-block;
}
```

When running in Storybook and using webpack to bundle the output included two class names:  "SelectPlanSubForm-module__optionLabel___NXcAg forms-module__label___W7Ul5".  However when using esbuild and this plugin, only one class name was included: "SelectPlanSubForm-module__optionLabel_x2lRna100".  That meant that the element did not recieve any of the styling defined in "forms.module.css"

**Comment by mhsdesign** [comment]
Hi ;) i was in need of this feature too as discussed here: https://github.com/indooorsman/esbuild-css-modules-plugin/issues/53

but in the end i made my own plugin: https://github.com/mhsdesign/esbuild-plugin-lightningcss-modules

**Comment by indooorsman** [comment]
you can try the dev version by 
```shell
npm i esbuild-css-modules-plugin@v3-dev
``` 
it supports compose & inject but may be buggy since I haven't did full testing 😂 I would really appreciate it if you could try it out and give feedback

@mhsdesign fyi
