### ISSUE TITLE
Loading CSS from an external library

### ISSUE THREAD

**Issue by dospunk** [indooorsman/esbuild-css-modules-plugin#54]
When trying to load CSS from an external library, the plugin assumes that it is in the same directory as the current file

ex. for a file named `src/foo/bar.ts`
```ts
import styleSheet from "my-external-lib/themes/light.css" assert { type: "css" };
// do things with stylesheet
```
An error is thrown saying 

ENOENT: no such file or directory, open 'path-to-my-repo/src/foo/my-external-lib/themes/light.css'

**Comment by indooorsman** [comment]
Could you provide full configuration of esbuild?
