### ISSUE TITLE
Capitalized CSS classes are not emitted

### ISSUE THREAD

**Issue by Kh4n** [indooorsman/esbuild-css-modules-plugin#55]
I am not sure if this is a bug or a feature but I will document it here for others

Capitalized CSS classes are not emitted in the resulted code in React + TSX:

App.module.css
```css
.App {
    color: red;
}
```

App.tsx
```tsx
import styles from './App.module.css'

export function App() {
    return (
        <div className={styles.App}>Hello</div>
    )
}
```

HTML Output:
```
<div>Hello</div>
```

Using a lowercase style name (eg. `.app` + `styles.app`) works fine

**Comment by indooorsman** [comment]
Hi, what version of plugin are you using?
________________________________
发件人: Asad-ullah Khan ***@***.***>
发送时间: Saturday, July 1, 2023 3:44:52 AM
收件人: indooorsman/esbuild-css-modules-plugin ***@***.***>
抄送: Subscribed ***@***.***>
主题: [indooorsman/esbuild-css-modules-plugin] Capitalized CSS classes are not emitted (Issue #55)


I am not sure if this is a bug or a feature but I will document it here for others

Capitalized CSS classes are not emitted in the resulted code in React + TSX:

App.module.css

.App {
    color: red;
}

App.tsx

import styles from './App.module.css'

export function App() {
    return (
        <div className={styles.App}>Hello</div>
    )
}

HTML Output:

<div>Hello</div>


Using a lowercase style name (eg. .app) works fine

―
