### ISSUE TITLE
Docs for `emitDeclarationFile`

### ISSUE THREAD

**Issue by bradenhs** [indooorsman/esbuild-css-modules-plugin#57]
Seems like a great feature! Don't see any docs for it though and am not exactly sure how it works e.g. where does the generated d.ts file end up? So far I haven't been able to make it work.

**Comment by indooorsman** [comment]
Hi @bradenhs,
are u using v3? if so the .d.ts would be generated in the `outdir` of your esbuild config

**Comment by bradenhs** [comment]
Yep was using v3. Took a look at the code though and things didn't seem too complicated so I ended up rolling my own plugin tailored to my use case (not published anywhere - just private to my project). Generating a `.d.ts` with the plugin is neat idea. Really useful. Thanks!
