### ISSUE TITLE
Build crashes when used with "write: false"

### ISSUE THREAD

**Issue by eTallang** [indooorsman/esbuild-css-modules-plugin#59]
Hi!

When developing locally, we use esbuild watch with `write: false` in the esbuild config. We do this so that we have greater control over how many files we write to the file system. However, it appears that the `esbuild-css-modules-plugin` throws the following error when we set `write: false`:

``` sh
✘ [ERROR] ENOENT: no such file or directory, open '<long-path>/dist/react/badge.css' [plugin esbuild-css-modules-plugin]
```

Would it be possible for the plugin to either create the folder before writing to the disk (and thus removing the error), or respect the `write` setting and return the CSS in memory like the rest of the build?

It's worth mentioning that the file _is_ written to the disk, so the error only appears in the logs on the first build, when the folder is empty.

**Comment by indooorsman** [comment]
It's reasonable to respect the `write` setting, will fix this issue in next version, thanks.
