### ISSUE TITLE
Changes to file `test/components/hello.world.jsx` are lost

### ISSUE THREAD

**Issue by maestrow** [indooorsman/esbuild-css-modules-plugin#6]
Changes to file `test/components/hello.world.jsx` are lost (rewritten with this commit: https://github.com/indooorsman/esbuild-css-modules-plugin/commit/9e426f5b679101b9400a6146429ef8ce2e31eef3#diff-b9ff8c20d74d99f9fd7ea9244e1d89a896466cee6737312c9686bb45851a454a). I think that was happen accidentally, so it would be nice to restore them :).

_Originally posted by @maestrow in https://github.com/indooorsman/esbuild-css-modules-plugin/issues/2#issuecomment-898848515_

**Comment by indooorsman** [comment]
@maestrow restored, sorry for the mistake
