### ISSUE TITLE
enable configuration of targets for lightningcss

### ISSUE THREAD

**Issue by mpech** [indooorsman/esbuild-css-modules-plugin#60]
Purpose is to support older browsers which do not implement css nesting

as of https://github.com/indooorsman/esbuild-css-modules-plugin/blob/main/lib/css.helper.js#L269
```

  bundle(fullpath, opt) {
    this.__result_cache__.delete(fullpath);
    const { options } = this.build.context;
    const bundleCssConfig = {
      filename: fullpath,
      cssModules: {
        dashedIdents: options?.dashedIndents,
        pattern: options?.pattern ?? `${opt?.prefix ?? ''}__[local]_[hash]__${opt?.suffix ?? ''}`
      },
      drafts: {
        customMedia: true,
        nesting: true
      },
      errorRecovery: true,
      minify: false,
      sourceMap: false,
      projectRoot: this.build.context.buildRoot,
      targets: {
        chrome: 112 << 16
      }
```
targets is chrome 112 which does not translate
`.x { & *{ color: red } }`
to
`.x * {color: red}`

is it possible to enable the configuration of targets (and also drafts)?

**Comment by indooorsman** [comment]
make sense, I will add more configurations for lightningcss in next version, thanks.

**Comment by indooorsman** [comment]
v3.1.0 published with more lightning css options
