### ISSUE TITLE
Invalid path on Windows

### ISSUE THREAD

**Issue by mcosand-caltopo** [indooorsman/esbuild-css-modules-plugin#61]
Very similar to #12 - when I try to run a build on a Windows machines, I'll get an error like
`    1 | import "esbuild-css-modules-plugin-ns-css:src\downstream\tile-downloads\components\styles.module.css"; > src/downstream/tile-downloads/index.module.css:1:7 | error: Do not know how to load path: esbuild-css-modules-plugin-ns-css:srcdownstream     ile-downloadsindex.module.css`. Build is finishing on v2.7.1, but not 3.0.0 or 3.0.3.

My configuration is
```
        cssModulesPlugin({
          generateScopedName: '[local]-[hash:base64:5]',
          v2: true
        }),
```

**Comment by indooorsman** [comment]
👍 Thanks for reporting, I will fix it asap
