### ISSUE TITLE
Allow to customize emitted name

### ISSUE THREAD

**Issue by Ayc0** [indooorsman/esbuild-css-modules-plugin#62]
In vite, we have access to `generateScopedName` (see docs https://vitejs.dev/config/shared-options.html#css-modules) (which itself comes from [postcss-modules](https://github.com/madyankin/postcss-modules)), and in webpack to `getLocalIdent` (see docs https://webpack.js.org/loaders/css-loader/#getlocalident) to customize the name of the emitted classnames

Could something like this be added to this plugin too?

**Comment by indooorsman** [comment]
see https://github.com/indooorsman/esbuild-css-modules-plugin/blob/c39b4c8a0d95357c09baecf807077cb0442e7a97/index.d.ts#L71

**Comment by Ayc0** [comment]
But those are strings right? `generateScopedName` / `getLocalIdent` are functions that can be used to achieve more advanced customizations.

As this is built on top of lightningcss, I guess I should open the issue there instead of here

**Comment by indooorsman** [comment]
Yes you are right.
It's able to replace classnames in the plugin but I think it's not quite worth to do.
