### ISSUE TITLE
css-tree should not be in devDependencies

### ISSUE THREAD

**Issue by cedeber** [indooorsman/esbuild-css-modules-plugin#8]
Hello, css-tree is not installed from npm as it is in the devDeps.

**Comment by marcin-wosinek** [comment]
thanks for opening the issue! I just hit the same issue. As a temp solution:
```
npm install --save-dev css-tree
```

in the client project fixes the issue.

**Comment by cedeber** [comment]
Oh, thanks for doing it :-D

**Comment by indooorsman** [comment]
Thank you both very much ❤️

**Comment by indooorsman** [comment]
esbuild-css-modules-plugin@2.0.9  has been published to fix this issue, thanks again
